services:
  web:
    build: ./simple_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/Nikhil/Desktop/coding/practice/containers:/data  # Attach a volume for persistent storage

volumes:
 