version: '3.8'

services:
  web:
    build: ./simple_app           # Path to your app directory
    ports:
      - "5000:5000"               # Exposing port 5000
    depends_on:
      - redis                      # Ensuring Redis starts before the web service

  redis:
    image: "redis:latest"         # Using the official Redis image
    ports:
      - "6379:6379"                # Exposing Redis port
    volumes:
      - redis_data:/data           # Use named volumes for data persistence

# Declare named volumes
volumes:
  redis_data:                      # Named volume for Redis persistence