services:
  web:
    build: ./simple_app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/Nikhil/Desktop/coding/practice/containers:/data  # Bind mount to host directory

# Named volumes (only needed if you want named volumes)
volumes:
  # If you had named volumes, declare them here
  # redis_data:  # Uncomment if you are using named volumes instead